apiVersion: v1
kind: Namespace
metadata:
  name: fieldrepo-staging
  labels:
    app.kubernetes.io/part-of: field-repository
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
