pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "FieldRepositoryAndroid"
include(":app")

/*
 * ── THE OFFLINE TRACE ENGINE, VENDORED ────────────────────────────────────────────────────────
 *
 * Four PLAIN KOTLIN/JVM modules — not Android libraries — holding the raster-to-SVG engine: image
 * processing (:core-imaging), contour and skeleton vectorisation (:core-vector), the staged
 * pipeline over them (:core-pipeline) and the writers (:core-export). Roughly 21,000 lines, and
 * `src/` is byte-for-byte identical to the designer portal's copy, which is itself vendored from
 * `F:/Offline-Tracer`. `UPSTREAM-MANIFEST-KOTLIN.txt` records a SHA-256 for every file.
 *
 * NOT ANDROID LIBRARY MODULES, AND THAT IS THE LOAD-BEARING CHOICE. Nothing in these four touches
 * the Android SDK — no Bitmap, no Context, no android.graphics anywhere — so as Kotlin/JVM modules
 * their tests are ORDINARY JVM UNIT TESTS that run on `./gradlew test` with no emulator and no
 * device. Making them Android libraries would move every one of those tests behind an emulator and
 * buy nothing at all. Only `:app` depends on Android.
 *
 * That matters most for :core-pipeline's `ParityTest`, which replays fixtures generated by the
 * TYPESCRIPT engine (`docs/fixtures/`, the same three files `frontend/lib/trace/` is checked
 * against) through the Kotlin and asserts the same numbers. It is the only mechanical check in this
 * repository that the handset and the browser draw the same thing.
 *
 * `:core-native`, the fifth module upstream has, is deliberately NOT vendored — it is an optional
 * SIMD accelerator, and `:core-imaging` holds the reference implementation of every kernel in it.
 * Upstream's own settings file records that deleting it "would cost speed and change no output".
 * Bringing it would mean NDK toolchains and per-ABI native builds in a repository that has neither,
 * to make a trace faster that has not yet been measured as too slow.
 *
 * These declare no repositories of their own, so `FAIL_ON_PROJECT_REPOS` above is untouched by
 * them: `kotlinx-serialization-json`, the single external dependency across the four, resolves from
 * the `mavenCentral()` already declared here at the version `:app` already uses.
 */
include(":core-imaging")
include(":core-vector")
include(":core-pipeline")
include(":core-export")
