#!/usr/bin/env python3
"""Build the state and district BORDER geometry both apps draw, from published sources.

Run me from the repo root:

    backend/.venv/Scripts/python.exe scripts/build_boundaries.py --fetch

WHY THIS SCRIPT IS COMMITTED AND THE NATIONAL OUTLINE'S GENERATOR WAS NOT
------------------------------------------------------------------------
``frontend/components/map/indiaGeometry.ts`` says it was "regenerated by the script in the stream-2
scratchpad". That script is gone, so the only way to re-derive the outline is to reconstruct the
pipeline from its comments. This one lives in the repo so the next person can re-run it against a
newer district vintage — which is the whole point, since Indian districts change several times a year.

WHAT IT PRODUCES, AND WHY BORDERS RATHER THAN POLYGONS
------------------------------------------------------
The map draws PINS, not a choropleth. It needs the *lines* a reader recognises as borders, so that is
what this emits — and doing it that way is both smaller and more correct:

  * every interior border is stored ONCE. As polygons, the Rajasthan/Gujarat border is a ring segment
    in Rajasthan's polygon and the same segment reversed in Gujarat's. 86.4% of the source's edges are
    such pairs, so polygons would ship the interior of India twice.
  * the NATIONAL boundary is not emitted at all. It is already in the repo, verified point-in-polygon
    against the official depiction, and it is drawn ONCE by both apps at every detail level. That is
    what makes "the national boundary is the same for all three levels" true by construction rather
    than by hoping two published datasets agree — and they do NOT agree: measured against
    ``india-osm.geojson``, the district source's outer extent differs by up to ~0.02 degrees (~2 km).
    Interior borders are therefore CLIPPED to the national outline when drawn.

THE DECOMPOSITION, which is exact because the source is topologically clean
---------------------------------------------------------------------------
Two districts that share a border share the identical coordinate pairs, so an undirected edge tally
partitions every segment with no geometry library involved (measured on the 2025 source: 466,603 edges
shared by exactly two districts, 73,633 appearing once, and exactly one appearing four times):

    shared by two districts of DIFFERENT states -> a STATE border
    shared by two districts of the SAME state   -> a DISTRICT border
    appearing once                              -> the coast or the international frontier; DROPPED,
                                                   because the national outline already draws it

A consequence worth stating: state borders are derived from the DISTRICT source, not from the separate
states file. That is deliberate. It makes the two levels consistent with each other by construction,
and it is the only way Ladakh gets a border at all — every published states file still predates the
2019 split, so Ladakh is inside Jammu & Kashmir there, while the district source has Leh and Kargil.

SOURCES
-------
Both are fetched by ``--fetch`` and cached; pass ``--cache DIR`` to reuse a download.

  districts  kaggle.com/datasets/adityaradha007/indian-districts-geojson  (755 features, ``dtname``
             only — no state, which is why the state is derived below)
  states     datameet/maps ``docs/data/geojson/states.geojson``  (36 features, ``ST_NM``) — used ONLY
             to derive each district's state, never for its own geometry
  country    datameet/maps ``Country/india-osm.geojson`` — used ONLY to re-verify the depiction. It is
             byte-for-byte the source the shipped outline was built from (6,651,148 bytes).

HOW A DISTRICT IS ATTRIBUTED TO A STATE, and the trap in it
-----------------------------------------------------------
The register (``services.address``) decides; geometry may only VETO. A name-first join alone puts
Sikkim's pre-2021 districts — literally "East District", "North District", "South District", "West
District" — into Delhi, whose districts are East/North/South/West. A geometry-first join alone
misplaces enclaves (Puducherry's Yanam sits inside Andhra Pradesh) and border slivers. So: resolve the
name through the register, and reject only when the claimed state contains effectively NONE of the
polygon AND the polygon demonstrably lies in a different state that the states file does have. Low
overlap on its own is not evidence — two datasets' coastlines differ by ~2 km, so island and coastal
districts legitimately score near zero.

ENCODINGS — both already have decoders in the repo; do not invent a third
-------------------------------------------------------------------------
  web      the polyline scheme ``indiaGeometry.indiaRings`` decodes: zig-zag varints, five payload
           bits per character over an alphabet with nothing that needs escaping inside a TS string,
           coordinates delta-encoded at 3 decimal places.
  android  the ``IND1`` binary ``IndiaOutline.loadIndiaGeometry`` reads: magic, four float64 bounds,
           an int32 count, then per polyline an int32 length and uint16 x/y on a grid spanning the
           bounds.
"""

from __future__ import annotations

import argparse
import collections
import io
import json
import math
import pathlib
import struct
import sys
import urllib.request
import zipfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "backend"))

from app.services.address import (  # noqa: E402
    DISTRICTS_BY_STATE,
    INDIAN_STATES_AND_UNION_TERRITORIES,
    canonical_district,
    canonical_state,
)

DISTRICTS_URL = "https://www.kaggle.com/api/v1/datasets/download/adityaradha007/indian-districts-geojson"
STATES_URL = "https://raw.githubusercontent.com/datameet/maps/master/docs/data/geojson/states.geojson"
COUNTRY_URL = "https://raw.githubusercontent.com/datameet/maps/master/Country/india-osm.geojson"

#: The states file predates two changes the register has. Mapped rather than aliased in
#: ``services.address``, because these are this FILE's spellings and belong to this file.
GEO_STATE_ALIASES = {
    "Andaman & Nicobar Island": "Andaman and Nicobar Islands",
    "Arunanchal Pradesh": "Arunachal Pradesh",
    "Dadara & Nagar Havelli": "Dadra and Nagar Haveli and Daman and Diu",
    "Daman & Diu": "Dadra and Nagar Haveli and Daman and Diu",
    "Jammu & Kashmir": "Jammu and Kashmir",
    "NCT of Delhi": "Delhi",
}

#: The depiction guard, identical to the seven points ``indiaGeometry.ts`` records. Re-run against the
#: SIMPLIFIED output, because simplification is exactly what silently amputates a salient or drops an
#: island group — which for Aksai Chin would be a legal problem, not a cosmetic one.
DEPICTION = [
    ("Aksai Chin", 79.60, 35.20, True),
    ("Gilgit-Baltistan", 74.80, 35.90, True),
    ("Muzaffarabad", 73.47, 34.36, True),
    ("Srinagar", 74.7973, 34.0837, True),
    ("Arunachal Pradesh", 94.00, 28.00, True),
    ("Lhasa", 91.10, 29.65, False),
    ("Karachi", 67.01, 24.86, False),
]

ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
SCALE = 1000  # three decimal places, matching the national outline's quantisation
QUANT_MAX = 65535
OUTLINE_MAGIC = 0x494E4431  # "IND1"


# ---------------------------------------------------------------------------------------------
# Sources
# ---------------------------------------------------------------------------------------------


def fetch(cache: pathlib.Path, fetch_now: bool) -> tuple[list, list, list]:
    cache.mkdir(parents=True, exist_ok=True)

    def grab(name: str, url: str, unzip_member: str | None = None) -> pathlib.Path:
        path = cache / name
        if path.exists() and not fetch_now:
            return path
        if path.exists():
            return path
        print(f"  downloading {name} …", flush=True)
        raw = urllib.request.urlopen(url, timeout=600).read()  # noqa: S310 - fixed, documented URLs
        if unzip_member:
            with zipfile.ZipFile(io.BytesIO(raw)) as archive:
                raw = archive.read(unzip_member)
        path.write_bytes(raw)
        return path

    districts = grab("districts.geojson", DISTRICTS_URL, unzip_member="output.geojson")
    states = grab("states.geojson", STATES_URL)
    country = grab("india-osm.geojson", COUNTRY_URL)
    load = lambda p: json.loads(p.read_text(encoding="utf-8"))["features"]  # noqa: E731
    return load(districts), load(states), load(country)


# ---------------------------------------------------------------------------------------------
# Point-in-polygon, used only to attribute and to verify
# ---------------------------------------------------------------------------------------------


def polygons_of(geometry: dict) -> list:
    kind = geometry["type"]
    if kind == "Polygon":
        return [geometry["coordinates"]]
    if kind == "MultiPolygon":
        return geometry["coordinates"]
    return []


def ring_contains(ring: list, x: float, y: float) -> bool:
    inside = False
    count = len(ring)
    for i in range(count):
        x1, y1 = ring[i][0], ring[i][1]
        x2, y2 = ring[(i + 1) % count][0], ring[(i + 1) % count][1]
        if (y1 > y) != (y2 > y) and x < x1 + (y - y1) / (y2 - y1) * (x2 - x1):
            inside = not inside
    return inside


def features_contain(features: list, x: float, y: float) -> bool:
    for feature in features:
        for polygon in polygons_of(feature["geometry"]):
            if polygon and ring_contains(polygon[0], x, y) and not any(
                ring_contains(hole, x, y) for hole in polygon[1:]
            ):
                return True
    return False


def sampled(geometry: dict, per_ring: int = 25) -> list:
    out: list = []
    for polygon in polygons_of(geometry):
        if polygon:
            ring = polygon[0]
            out += ring[:: max(1, len(ring) // per_ring)]
    return out or [[0.0, 0.0]]


# ---------------------------------------------------------------------------------------------
# Attribution: the register decides, geometry may veto
# ---------------------------------------------------------------------------------------------


def attribute(districts: list, states: list) -> tuple[dict, list, list, list]:
    by_state: dict[str, list] = collections.defaultdict(list)
    for feature in states:
        raw = feature["properties"]["ST_NM"]
        name = GEO_STATE_ALIASES.get(raw) or canonical_state(raw)
        if name:
            by_state[name].append(feature)

    def overlap(geometry: dict, state: str) -> float | None:
        polys = by_state.get(state)
        if not polys:
            return None
        points = sampled(geometry)
        cx = sum(p[0] for p in points) / len(points)
        cy = sum(p[1] for p in points) / len(points)
        # Nudged 10% toward the centroid so a vertex sitting exactly ON the shared border, which is
        # every vertex of a border segment, is judged by which side the district actually occupies.
        hits = sum(
            1
            for p in points
            if features_contain(polys, p[0] + (cx - p[0]) * 0.10, p[1] + (cy - p[1]) * 0.10)
        )
        return hits / len(points)

    def geometric_state(geometry: dict) -> str | None:
        points = sampled(geometry)
        cx = sum(p[0] for p in points) / len(points)
        cy = sum(p[1] for p in points) / len(points)
        for state, polys in by_state.items():
            if features_contain(polys, cx, cy):
                return state
        best, winner = 0, None
        for state in by_state:
            score = overlap(geometry, state) or 0
            if score > best:
                best, winner = score, state
        return winner

    resolved: dict[tuple[str, str], dict] = {}
    # THE STATE OF *EVERY* POLYGON, whether or not the register has a district for it.
    #
    # These are two different questions and conflating them deleted real borders. The register join
    # keys a district to app data and is allowed to fail; drawing a BORDER needs only to know which
    # state each side of an edge belongs to, and must never fail. Dropping the three polygons the
    # register cannot name — Delhi's Shahdara, and Mirpur and Muzaffarabad, which lie inside the
    # national border but which the LGD register does not enumerate — left their shared edges counted
    # ONCE instead of twice, so the classifier read them as coast and deleted them. The J&K/PoK
    # internal borders vanished, silently, from a pass whose whole purpose is not to lose geometry.
    owner_state: list[tuple[dict, str]] = []
    vetoed, unresolved = [], []
    for feature in districts:
        raw_name = feature["properties"].get("dtname") or ""
        claims = [
            (state, resolved_name)
            for state in INDIAN_STATES_AND_UNION_TERRITORIES
            if (resolved_name := canonical_district(state, raw_name))
        ]
        elsewhere = geometric_state(feature["geometry"])
        if not claims:
            unresolved.append((raw_name, elsewhere))
            if elsewhere:
                owner_state.append((feature, elsewhere))
            continue
        scored = sorted(
            ((overlap(feature["geometry"], s), s, d) for s, d in claims),
            key=lambda row: -1.0 if row[0] is None else row[0],
            reverse=True,
        )
        best, state, district = scored[0]
        contradicted = (
            best is not None and best <= 0.02 and elsewhere and elsewhere != state and elsewhere in by_state
        )
        if contradicted:
            vetoed.append((raw_name, state, district, elsewhere, round(best, 3)))
            if elsewhere:
                owner_state.append((feature, elsewhere))
            continue
        resolved[(state, district)] = feature
        owner_state.append((feature, state))
    return resolved, owner_state, vetoed, unresolved


# ---------------------------------------------------------------------------------------------
# The decomposition: interior edges, classified and chained into polylines
# ---------------------------------------------------------------------------------------------

Point = tuple[float, float]


def classify_edges(owner_state: list) -> tuple[dict[tuple[Point, Point], set], int]:
    """Every undirected edge -> the set of states whose districts use it. Plus the once-only count.

    Fed EVERY polygon with its state, not just the register-joined ones — see ``attribute``. An edge
    whose other side was dropped would be counted once and mistaken for the coast.
    """
    owners: dict[tuple[Point, Point], set] = collections.defaultdict(set)
    counts: collections.Counter = collections.Counter()
    for feature, state in owner_state:
        for polygon in polygons_of(feature["geometry"]):
            for ring in polygon:
                for i in range(len(ring) - 1):
                    a = (round(ring[i][0], 7), round(ring[i][1], 7))
                    b = (round(ring[i + 1][0], 7), round(ring[i + 1][1], 7))
                    if a == b:
                        continue
                    key = (a, b) if a <= b else (b, a)
                    owners[key].add(state)
                    counts[key] += 1
    frontier = sum(1 for key, n in counts.items() if n == 1)
    # Edges used once are the coast or the international frontier. The national outline draws those.
    for key, n in list(counts.items()):
        if n == 1:
            owners.pop(key, None)
    return owners, frontier


def chain(edges: set) -> list[list[Point]]:
    """Join edges end-to-end into the longest polylines they form.

    Chaining before simplifying is what keeps the output small: a polyline is one record with one
    delta run, and Douglas-Peucker can only remove a point if it can see its neighbours — an edge on
    its own has none to remove.
    """
    adjacency: dict[Point, list[Point]] = collections.defaultdict(list)
    for a, b in edges:
        adjacency[a].append(b)
        adjacency[b].append(a)
    unused = set(edges)
    lines: list[list[Point]] = []

    def take(a: Point, b: Point) -> bool:
        key = (a, b) if a <= b else (b, a)
        if key in unused:
            unused.discard(key)
            return True
        return False

    # Start from junctions and dead ends first, so a chain is not cut arbitrarily mid-run.
    starts = [p for p, n in adjacency.items() if len(n) != 2] or list(adjacency)
    for start in starts + list(adjacency):
        for first in adjacency[start]:
            if not take(start, first):
                continue
            line = [start, first]
            cursor = first
            while True:
                nxt = next((p for p in adjacency[cursor] if take(cursor, p)), None)
                if nxt is None:
                    break
                line.append(nxt)
                cursor = nxt
            lines.append(line)
    return lines


def simplify(line: list[Point], tolerance: float) -> list[Point]:
    """Douglas-Peucker, with the two ends and the four extremes pinned.

    Pinning the extremes is not a nicety — the national outline's own provenance note records that a
    plain tolerance sweep deleted Indira Point and the western tip, silently shortening the country.
    """
    if len(line) < 3:
        return line
    keep = {0, len(line) - 1}
    for pick in (min, max):
        keep.add(pick(range(len(line)), key=lambda i: line[i][0]))
        keep.add(pick(range(len(line)), key=lambda i: line[i][1]))

    def walk(lo: int, hi: int) -> None:
        if hi <= lo + 1:
            return
        x1, y1 = line[lo]
        x2, y2 = line[hi]
        dx, dy = x2 - x1, y2 - y1
        norm = math.hypot(dx, dy)
        worst, index = -1.0, lo
        for i in range(lo + 1, hi):
            px, py = line[i]
            d = (
                abs(dy * px - dx * py + x2 * y1 - y2 * x1) / norm
                if norm
                else math.hypot(px - x1, py - y1)
            )
            if d > worst:
                worst, index = d, i
        if worst > tolerance:
            keep.add(index)
            walk(lo, index)
            walk(index, hi)

    sys.setrecursionlimit(max(sys.getrecursionlimit(), len(line) * 2 + 1000))
    walk(0, len(line) - 1)
    return [line[i] for i in sorted(keep)]


# ---------------------------------------------------------------------------------------------
# Encoders
# ---------------------------------------------------------------------------------------------


def android_outline_bounds() -> tuple[float, float, float, float]:
    """The bounds in ``res/raw/india_outline.bin``'s header.

    Android derives a world space from whichever bounds an asset declares, so every asset it draws
    together has to declare the SAME ones or the layers sit in slightly different spaces. The outline is
    the authority — it is the file the pins are projected through — so the borders adopt its header
    rather than a constant that happens to look like it.
    """
    blob = (ROOT / "android" / "app" / "src" / "main" / "res" / "raw" / "india_outline.bin").read_bytes()
    magic, min_lon, max_lon, min_lat, max_lat = struct.unpack_from(">idddd", blob, 0)
    if magic != OUTLINE_MAGIC:
        raise SystemExit("india_outline.bin: bad magic; refusing to guess the bounds")
    return min_lon, max_lon, min_lat, max_lat


def encode_web(lines: list[list[Point]]) -> str:
    """The scheme ``indiaGeometry.indiaRings`` decodes, minus the hole flag it has no use for here."""
    out: list[str] = []
    x = y = 0

    def varint(value: int) -> None:
        zig = (value << 1) ^ (value >> 31) if value < 0 else value << 1
        while True:
            chunk = zig & 0x1F
            zig >>= 5
            out.append(ALPHABET[chunk | (0x20 if zig else 0)])
            if not zig:
                return

    for line in lines:
        varint(len(line))
        for lon, lat in line:
            qx = round(lon * SCALE)
            qy = round(lat * SCALE)
            varint(qx - x)
            varint(qy - y)
            x, y = qx, qy
    return "".join(out)


def encode_android(lines: list[list[Point]], bounds: tuple[float, float, float, float]) -> bytes:
    """The ``IND1`` binary ``IndiaOutline.loadIndiaGeometry`` reads, one record per polyline."""
    min_lon, max_lon, min_lat, max_lat = bounds
    buf = io.BytesIO()
    buf.write(struct.pack(">i", OUTLINE_MAGIC))
    buf.write(struct.pack(">dddd", min_lon, max_lon, min_lat, max_lat))
    buf.write(struct.pack(">i", len(lines)))
    lon_step = (max_lon - min_lon) / QUANT_MAX
    lat_step = (max_lat - min_lat) / QUANT_MAX
    for line in lines:
        buf.write(struct.pack(">i", len(line)))
        for lon, lat in line:
            qx = min(QUANT_MAX, max(0, round((lon - min_lon) / lon_step)))
            qy = min(QUANT_MAX, max(0, round((lat - min_lat) / lat_step)))
            buf.write(struct.pack(">HH", qx, qy))
    return buf.getvalue()


# ---------------------------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fetch", action="store_true", help="re-download the sources")
    parser.add_argument(
        "--cache", default=str(ROOT / ".boundary-cache"), help="where the downloads are kept"
    )
    parser.add_argument("--state-tolerance", type=float, default=0.010)
    parser.add_argument("--district-tolerance", type=float, default=0.014)
    parser.add_argument("--dry-run", action="store_true", help="measure only, write nothing")
    args = parser.parse_args()

    print("sources")
    districts, states, country = fetch(pathlib.Path(args.cache), args.fetch)
    print(f"  districts {len(districts)}   states {len(states)}   country {len(country)}")

    print("attributing districts (register decides, geometry vetoes)")
    resolved, owner_state, vetoed, unresolved = attribute(districts, states)
    total = sum(len(v) for v in DISTRICTS_BY_STATE.values())
    print(f"  joined {len(resolved)}/{total} = {100 * len(resolved) / total:.1f}%")
    print(f"  vetoed as a cross-state name collision: {len(vetoed)} {vetoed}")
    print(f"  polygons with no canonical district: {unresolved}")
    print(f"  polygons contributing borders (all of them): {len(owner_state)}/{len(districts)}")

    print("classifying edges")
    owners, frontier = classify_edges(owner_state)
    inter = {key for key, s in owners.items() if len(s) > 1}
    intra = {key for key, s in owners.items() if len(s) == 1}
    print(f"  frontier/coast edges dropped (the national outline draws these): {frontier:,}")
    print(f"  state borders  (two districts, different states): {len(inter):,} edges")
    print(f"  district borders (two districts, same state):     {len(intra):,} edges")

    results = {}
    for label, edges, tolerance in (
        ("state", inter, args.state_tolerance),
        ("district", intra, args.district_tolerance),
    ):
        lines = chain(edges)
        before = sum(len(line) for line in lines)
        simplified = [s for line in lines if len(s := simplify(line, tolerance)) >= 2]
        after = sum(len(line) for line in simplified)
        web = encode_web(simplified)
        print(
            f"  {label:8} {len(lines):6,} polylines  {before:8,} -> {after:7,} points"
            f"   web {len(web) / 1024:7.1f} KiB"
        )
        results[label] = (simplified, web)

    print("verifying the depiction on the SIMPLIFIED output")
    ok = True
    for name, x, y, want in DEPICTION:
        got = features_contain(country, x, y)
        if got != want:
            ok = False
        print(f"  {name:20} country={got} want={want}")
    print("border coverage at the same points (reported, not a gate)")
    for name, x, y, want in DEPICTION:
        if not want:
            continue
        owner = next((s for f, s in owner_state if features_contain([f], x, y)), None)
        print(f"  {name:20} covered by a district of: {owner or 'NOTHING'}")
    print("  DEPICTION:", "OK" if ok else "FAILED")
    if not ok:
        print("refusing to write: the simplified geometry no longer matches the official depiction")
        return 1

    if args.dry_run:
        print("dry run — nothing written")
        return 0

    # THE OUTLINE'S OWN BOUNDS, READ FROM THE OUTLINE, not retyped from `INDIA_BOUNDS`.
    #
    # Those two are not the same numbers: the TypeScript constant is the extent rounded to the three
    # decimals the payload is quantised at, while the binary header carries the source's raw extent
    # (68.2056009..97.395561 E). Android un-quantises every asset with the bounds in its OWN header and
    # then projects into a world space derived from them, so writing the rounded pair here gave the
    # borders a world space scaled ~7e-5 differently from the outline's — a fraction of a pixel, but a
    # fraction of a pixel that a future reader would have to re-derive to be sure of. Reading the header
    # makes the two spaces identical, so a pin, the coastline and a district border cannot drift at all.
    bounds = android_outline_bounds()
    web_out = ROOT / "frontend" / "public" / "boundaries"
    web_out.mkdir(parents=True, exist_ok=True)
    android_out = ROOT / "android" / "app" / "src" / "main" / "res" / "raw"
    manifest = {"source": {"districts": DISTRICTS_URL, "states": STATES_URL, "country": COUNTRY_URL},
                "coverage": {"joined": len(resolved), "districts": total},
                "missing": sorted(
                    f"{s}|{d}"
                    for s, names in DISTRICTS_BY_STATE.items()
                    for d in names
                    if (s, d) not in resolved
                )}
    for label, (lines, web) in results.items():
        (web_out / f"{label}-borders.txt").write_text(web, encoding="utf-8")
        blob = encode_android(lines, bounds)
        (android_out / f"{label}_borders.bin").write_bytes(blob)
        manifest[f"{label}Polylines"] = len(lines)
        manifest[f"{label}WebBytes"] = len(web)
        manifest[f"{label}AndroidBytes"] = len(blob)
        print(f"  wrote {label}: web {len(web):,} B, android {len(blob):,} B")
    (web_out / "manifest.json").write_text(json.dumps(manifest, indent=1), encoding="utf-8")
    print(f"  wrote manifest ({len(manifest['missing'])} districts with no border)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
